apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 6
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
        - name: was
          envFrom:
            - secretRef:
                name: ljh-login-secret
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
